spring:
  datasource:
    url: jdbc:mysql://15.223.71.48:31065/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ece9014
    password: uwoece9014
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 15.223.71.48 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 31679 # Redis服务器连接端口
    password: ece9014 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

minio:
  endpoint: http://192.168.3.101:9090 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info

logstash:
  host: logstash