replicaCount: 1

image:
  repository: genshushu123/mall-admin
  pullPolicy: Always
  tag: "1.0"

service:
  type: ClusterIP
  port: 8080
serviceAccount:
  create: true
  name: mall-admin
ingress:
  enabled: false
autoscaling:
  enabled: false
resources: {}

nodeSelector: {}

tolerations: []

affinity: []